export const DISCORD_COMMAND_PREFIX = "CISCC ";
export const TRASH_BIN_EMOJI = "🗑️";

export const SERVICE_MESSAGE_PREFIX = "[CISCC-SERVICE-MESSAGE] ";
export const SERVICE_MESSAGE_MATCHER = /^\[CISCC-SERVICE-MESSAGE]/;
